apiVersion: apps/v1
kind: Deployment
metadata:
  name: ea-cart-deployment
  labels:
    app: ea-cart
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ea-cart
  template:
    metadata:
      labels:
        app: ea-cart
    spec:
      containers:
        - name: ea-cart
          image: bruesky/ea_cart
          ports:
            - containerPort: 8085
---
apiVersion: v1                  # API version
kind: Service                   # Type of kubernetes resource
metadata:
  name: ea-cart-service      # Name of the kubernetes resource
spec:
  type: ClusterIP              # Exposes the service by opening a port on each node
  selector:
    app: ea-cart
  ports:                        # Forward incoming connections on port 80 to the target port 80 in the Pod
    - name: http
      port: 8085 # Pod+Port
      targetPort: 8085 # Cluster IP or Service Name
