apiVersion: apps/v1
kind: Deployment
metadata:
  name: ea-product-deployment
  labels:
    app: ea-product
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ea-product
  template:
    metadata:
      labels:
        app: ea-product
    spec:
      containers:
        - name: ea-product
          image: bruesky/ea_product
          ports:
            - containerPort: 8083
---
apiVersion: v1                  # API version
kind: Service                   # Type of kubernetes resource
metadata:
  name: ea-product-service      # Name of the kubernetes resource
spec:
  type: ClusterIP              # Exposes the service by opening a port on each node
  selector:
    app: ea-product
  ports:                        # Forward incoming connections on port 80 to the target port 80 in the Pod
    - name: http
      port: 8083 # Pod+Port
      targetPort: 8083 # Cluster IP or Service Name
