apiVersion: apps/v1
kind: Deployment
metadata:
  name: ea-client-deployment
  labels:
    app: ea-client
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ea-client
  template:
    metadata:
      labels:
        app: ea-client
    spec:
      containers:
      - name: ea-client
        image: bruesky/ea_client_simple
        ports:
        - containerPort: 80
---
apiVersion: v1                  # API version
kind: Service                   # Type of kubernetes resource
metadata:
  name: ea-client-service      # Name of the kubernetes resource
spec:
  type: NodePort                # Exposes the service by opening a port on each node
  selector:
    app: ea-client     
  ports:                        # Forward incoming connections on port 80 to the target port 80 in the Pod
  - name: http
    port: 80 # Pod+Port
    targetPort: 80 # Cluster IP or Service Name
    nodePort: 30001 # Node IP+Port