excludeUrls: /user/login,/user/register
authUrl: http://localhost:9999

zuul:
  routes:
    test:
      path: /api/test/**
      url: http://localhost:8081/test/
    user:
      path: /api/user/**
      url: http://localhost:8082/user/
    product:
      path: /api/product/**
      url: http://localhost:8083/product/
