apiVersion: apps/v1
kind: Deployment
metadata:
  name: ea-hellosb-deployment
  labels:
    app: ea-hellosb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ea-hellosb
  template:
    metadata:
      labels:
        app: ea-hellosb
    spec:
      containers:
        - name: ea-hellosb
          image: bruesky/ea_hellosb
          ports:
            - containerPort: 8081
---
apiVersion: v1                  # API version
kind: Service                   # Type of kubernetes resource
metadata:
  name: ea-hellosb-service      # Name of the kubernetes resource
spec:
  type: ClusterIP              # Exposes the service by opening a port on each node
  selector:
    app: ea-hellosb
  ports:                        # Forward incoming connections on port 80 to the target port 80 in the Pod
    - name: http
      port: 8081 # Pod+Port
      targetPort: 8081 # Cluster IP or Service Name
