version : '3'
services:
  ea_mysql:
    image: mysql:5.7
    container_name: ea_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=ea_skeleton
    ports:
      - 3306:3306
#    volumes:
#      - ./sql:/docker-entrypoint-initdb.d
    restart: always

  ea_redis:
    image: redis:latest
    container_name: ea_redis
    ports:
      - 6379:6379
    restart: always