apiVersion: apps/v1
kind: Deployment
metadata:
  name: ea-redis-deployment
  labels:
    app: ea-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ea-redis
  template:
    metadata:
      labels:
        app: ea-redis
    spec:
      containers:
      - name: ea-redis
        image: redis:latest
        ports:
        - containerPort: 6379
---
apiVersion: v1                  
kind: Service                  
metadata:
  name: ea-redis-service      
spec:
  type: NodePort                
  selector:
    app: ea-redis    
  ports:                        
  - port: 6379 
    targetPort: 6379 
    nodePort: 30379