apiVersion: apps/v1
kind: Deployment
metadata:
  name: ea-gateway-deployment
  labels:
    app: ea-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ea-gateway
  template:
    metadata:
      labels:
        app: ea-gateway
    spec:
      containers:
        - name: ea-gateway
          image: bruesky/ea_gateway
          ports:
            - containerPort: 8080
---
apiVersion: v1                  # API version
kind: Service                   # Type of kubernetes resource
metadata:
  name: ea-gateway-service      # Name of the kubernetes resource
spec:
  type: ClusterIP              # Exposes the service by opening a port on each node
  selector:
    app: ea-gateway
  ports:                        # Forward incoming connections on port 80 to the target port 80 in the Pod
    - name: http
      port: 8080 # Pod+Port
      targetPort: 8080 # Cluster IP or Service Name
