apiVersion: apps/v1
kind: Deployment
metadata:
  name: ea-order-deployment
  labels:
    app: ea-order
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ea-order
  template:
    metadata:
      labels:
        app: ea-order
    spec:
      containers:
        - name: ea-order
          image: bruesky/ea_order
          ports:
            - containerPort: 8084
---
apiVersion: v1                  # API version
kind: Service                   # Type of kubernetes resource
metadata:
  name: ea-order-service      # Name of the kubernetes resource
spec:
  type: ClusterIP              # Exposes the service by opening a port on each node
  selector:
    app: ea-order
  ports:                        # Forward incoming connections on port 80 to the target port 80 in the Pod
    - name: http
      port: 8084 # Pod+Port
      targetPort: 8084 # Cluster IP or Service Name
